os: osx
language: cpp
install:
- cmake --version
- rm -rf /usr/local/bin/cmake
- rm -rf /usr/local/bin/ctest
- rm -rf /usr/local/bin/cpack
- rm -rf /usr/local/bin/cmake-gui
- rm -rf /usr/local/bin/ccmake
- rm -rf /Applications/CMake.app/Contents/bin/cmake
- curl https://cmake.org/files/v3.17/cmake-3.17.0-Darwin-x86_64.tar.gz -O
- tar -xzf cmake-3.17.0-Darwin-x86_64.tar.gz
- sudo mv cmake-3.17.0-Darwin-x86_64/CMake.app /Applications
- sudo /Applications/CMake.app/Contents/bin/cmake-gui --install
- cmake --version
- brew update
- brew list git &>/dev/null || brew install git
- brew list pkg-config &>/dev/null || brew install pkg-config
- brew list qt &>/dev/null || brew install qt
- brew list boost &>/dev/null || brew install boost
- brew info boost
- brew upgrade boost
- brew info boost
- curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
cache:
  directories:
    botan
script:
- ls botan/
- bash build-botan.sh
- cmake . -DBOTAN_LIBRARY=botan/libbotan-2.a -DBOTAN_INCLUDE_DIR=botan/build/include -DCMAKE_PREFIX_PATH=$(brew --prefix qt5)
- make
- ASAN_OPTIONS=detect_leaks=0 bin/tests -- --test-base-dir "test"
- $(brew --prefix qt5)/bin/macdeployqt bin/PlaybookCreator.app -verbose=3 -dmg -no-strip
- bash deploy.sh bin/PlaybookCreator.dmg PlaybookCreator.dmg "PlaybookCreator for MacOSX" $GITHUB_TOKEN
