version: 2
jobs:
  build:
    docker:
      - image: ubuntu
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            apt update && apt install -y git build-essential cmake pkg-config qt5-default libboost-serialization-dev python golang-go
      - restore_cache:
          keys:
            - botan-cache-v2.6_3
      - run:
          name: Botan Library
          command: |
            if [ ! -d botan ]; then
              git clone https://github.com/randombit/botan botan
              cd botan
              git checkout 2.6.0
              python configure.py --disable-shared-library
              make
              cd ..
            fi
      - save_cache:
          key: botan-cache-v2.6_3
          paths:
            - botan
      - run:
          name: Build
          command: |
            cmake -D BOTAN_LIBRARY=botan/libbotan-2.a -D BOTAN_INCLUDE_DIR=botan/build/include .
            make
      - run:
          name: Copy Qt5 shared libaries
          command: |
            echo "disabled for now..consider using https://github.com/probonopd/linuxdeployqt"
      - store_artifacts:
          path: bin/PlaybookCreator
          destination: PlaybookCreator
      - run:
          name: Deploy
          command: |
            bash deploy.sh bin/PlaybookCreator PlaybookCreator "PlaybookCreator for Linux" $GITHUB_TOKEN
